version: '3'
services:
  react:
    build:
      context: .
      dockerfile: ./containers/react/Dockerfile
    command: sh -c "yarn start"
    volumes:
      - ./react:/usr/src/app
    ports:
      - 8000:3000
