name: Build & Push React App

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
      -
        name: Set up Docker Container
        shell: bash
        run: |
          docker compose build
          docker compose run --rm react yarn install
          docker compose up -d
      -
        name: Build React App
        shell: bash
        run: |
          docker compose exec react yarn build
      -
        name: Configure AWS Credencials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      -
        name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
      -
        name: Push React Image
        uses: docker/build-push-action@v2
        with:
          file: ./containers/react/Dockerfile
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/react-cd-test:${{ github.sha }}
