name: Build React App

on: [push]

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Container
        shell: bash
        run: |
          docker compose build
          docker compose run --rm react yarn install
          docker compose up -d
      -
        name: Build React App
        shell: bash
        run: |
          docker compose exec react yarn build
          docker compose exec react ls
          echo --------------
          ls react/test-app
